### ISSUE TITLE
[Enhancement] Write command descriptions on new lines

### ISSUE THREAD

**Issue by KwatMDPhD** [comonicon/Comonicon.jl#180]
<img width="1102" alt="Screen Shot 2022-02-12 at 10 44 19" src="https://user-images.githubusercontent.com/7741548/154121243-4a614df3-e48b-4b63-9770-47d949add04f.png">

The narrow window makes it look like the descriptions are on the 2nd line. But this is kind of nice. If the descriptions are written on their own lines, then there can be no limit to the length of descriptions.

Something like write(indent.(descriptionlines)).

**Comment by Roger-luo** [comment]
so I think having the description in new lines is a good idea but still not ideal since you can have a very long signature that needs multiple lines to print. So I think there are two things here:

- don't print verbose argument list in upper level help msg, and only print `mycommand <args>`
- print long command name's help message in new lines (basically that `man` uses)
